### ISSUE TITLE
Two of four motors spinning

### ISSUE THREAD

**Issue by HoserMatt** [BossHobby/Templates#5]
Flashed an original tinyhawk (MatekF411RX FRSKY). Everything seemed to work, but two of the four motors (which did work prior to flashing) no longer spin up. The front left (PIN0 - PB7) and back left motor (PIN3 - PB6) both work, but the front right (PIN1 - PB8) and back right (PIN2 - PB10) do not spin up. Did I flash the incorrect target or is there another way to identify motor outputs?

**Comment by chaotixtech** [comment]
This is not the place for support questions, please head over to our Discord server.
